apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:  
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order
        image: amradel2002/order-service
        
        ports:
        - containerPort: 5002
